grpcServer:
  user:
    register:
      ip: "172.17.0.4"
      port: "4040"
    auth:
      ip: "172.17.0.5"
      port: "4040"
    get:
      ip: "172.17.0.11"
      port: "4040"
    post:
      ip: "172.17.0.10"
      port: "4040"
