// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: postPost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Content    string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Visibility string `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
}

func (x *PostPostRequest) Reset() {
	*x = PostPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postPost_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPostRequest) ProtoMessage() {}

func (x *PostPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postPost_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPostRequest.ProtoReflect.Descriptor instead.
func (*PostPostRequest) Descriptor() ([]byte, []int) {
	return file_postPost_proto_rawDescGZIP(), []int{0}
}

func (x *PostPostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostPostRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type PostPostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PostPostReply) Reset() {
	*x = PostPostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postPost_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostPostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPostReply) ProtoMessage() {}

func (x *PostPostReply) ProtoReflect() protoreflect.Message {
	mi := &file_postPost_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPostReply.ProtoReflect.Descriptor instead.
func (*PostPostReply) Descriptor() ([]byte, []int) {
	return file_postPost_proto_rawDescGZIP(), []int{1}
}

func (x *PostPostReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DelArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ArticleId int64 `protobuf:"varint,2,opt,name=articleId,proto3" json:"articleId,omitempty"`
}

func (x *DelArticleRequest) Reset() {
	*x = DelArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postPost_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelArticleRequest) ProtoMessage() {}

func (x *DelArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postPost_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelArticleRequest.ProtoReflect.Descriptor instead.
func (*DelArticleRequest) Descriptor() ([]byte, []int) {
	return file_postPost_proto_rawDescGZIP(), []int{2}
}

func (x *DelArticleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DelArticleRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type DelArticleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DelArticleReply) Reset() {
	*x = DelArticleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postPost_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelArticleReply) ProtoMessage() {}

func (x *DelArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_postPost_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelArticleReply.ProtoReflect.Descriptor instead.
func (*DelArticleReply) Descriptor() ([]byte, []int) {
	return file_postPost_proto_rawDescGZIP(), []int{3}
}

func (x *DelArticleReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_postPost_proto protoreflect.FileDescriptor

var file_postPost_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x29, 0x0a, 0x0d,
	0x50, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x49, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32,
	0x8f, 0x01, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_postPost_proto_rawDescOnce sync.Once
	file_postPost_proto_rawDescData = file_postPost_proto_rawDesc
)

func file_postPost_proto_rawDescGZIP() []byte {
	file_postPost_proto_rawDescOnce.Do(func() {
		file_postPost_proto_rawDescData = protoimpl.X.CompressGZIP(file_postPost_proto_rawDescData)
	})
	return file_postPost_proto_rawDescData
}

var file_postPost_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_postPost_proto_goTypes = []interface{}{
	(*PostPostRequest)(nil),   // 0: proto.PostPostRequest
	(*PostPostReply)(nil),     // 1: proto.PostPostReply
	(*DelArticleRequest)(nil), // 2: proto.DelArticleRequest
	(*DelArticleReply)(nil),   // 3: proto.DelArticleReply
}
var file_postPost_proto_depIdxs = []int32{
	0, // 0: proto.PostPostService.PostPost:input_type -> proto.PostPostRequest
	2, // 1: proto.PostPostService.DelArticle:input_type -> proto.DelArticleRequest
	1, // 2: proto.PostPostService.PostPost:output_type -> proto.PostPostReply
	3, // 3: proto.PostPostService.DelArticle:output_type -> proto.DelArticleReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postPost_proto_init() }
func file_postPost_proto_init() {
	if File_postPost_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_postPost_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postPost_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostPostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postPost_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postPost_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelArticleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_postPost_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_postPost_proto_goTypes,
		DependencyIndexes: file_postPost_proto_depIdxs,
		MessageInfos:      file_postPost_proto_msgTypes,
	}.Build()
	File_postPost_proto = out.File
	file_postPost_proto_rawDesc = nil
	file_postPost_proto_goTypes = nil
	file_postPost_proto_depIdxs = nil
}
