databases:
  redis:
    domain: "172.17.0.5"
    port: "6379"
    user: 
    password:
  mysql:
    domain: "172.17.0.7"
    port: "3306"
    user: "root"
    password: "my-secret-pw"
    net: "tcp"
    databaseName: "user"
server:
  port: "4040"
